Added some more bash aliases and reorganized bashrc

diff --git a/src/bashrc b/src/bashrc
--- a/src/bashrc
+++ b/src/bashrc
@@ -3,59 +3,24 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
+# bash completion directory
 source $HOME/.bash_completion.d/*.sh
+
+# git prompt and git completion
 source /usr/share/git/completion/git-prompt.sh
 source /usr/share/git/completion/git-completion.bash
+
+# dircolors
+eval $(dircolors $HOME/.dir_colors)
 
 export EDITOR="/usr/bin/vim"
 export PAGER="/usr/bin/less"
 export LANG="en_US.UTF-8"
 
+# add ~/bin to path if it exists
 [ -d $HOME/bin ] && export PATH=${PATH}:${HOME}/bin
 
-alias cal='cal -3'
-alias df='df -h'
-alias du='du -sh'
-alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
-alias l.='ls -dF .* --color=auto'
-alias la='ls -hA --color=auto'
-alias less='less -R'
-alias ll='ls -lFh --color=auto'
-alias lla='ls -lhA --color=auto'
-alias lld='ls -ldFh --color=auto'
-alias ls='ls -hF --color=auto'
-alias mkdir='mkdir -p -v'
-
-# Optional aliases
-alias todo='todo.sh'
-#alias top='htop'
-#alias yogurt='yaourt'
-
-## Arch Linux specific aliases
-# Synchronize with repositories before upgrading packages that are out of date on the local system.
-alias pacupg='sudo pacman -Syu'
-# Install specific package(s) from the repositories
-alias pacin='sudo pacman -S'
-# Install specific package not from the repositories but from a file
-alias pacins='sudo pacman -U'
-# Remove the specified package(s), retaining its configuration(s) and required dependencies
-alias pacre='sudo pacman -R'
-# Remove the specified package(s), its configuration(s) and unneeded dependencies
-alias pacrem='sudo pacman -Rns'
-# Display information about a given package in the repositories
-alias pacrep='pacman -Si'
-# Search for package(s) in the repositories
-alias pacreps='pacman -Ss'
-# Display information about a given package in the local database
-alias pacloc='pacman -Qi'
-# Search for package(s) in the local database
-alias paclocs='pacman -Qs'
-
-
-
-
-eval $(dircolors $HOME/.dir_colors)
-
+# bash fixes and settings
 # Bash won't get SIGWINCH if another process is in the foreground.
 # Enable checkwinsize so that bash will check the terminal size when
 # it regains control.  #65623
@@ -68,17 +33,75 @@ shopt -s histappend
 # Disable Ctrl-S and Ctrl-Q from terminal sessions
 stty -ixon
 
-# Local change support
+# display error codes
+EC() { echo -e '\e[1;33m'retcode $?'\e[m'; }
+trap EC ERR
 
-[[ -r $HOME/.bashrc_local ]] && source $HOME/.bashrc_local
+# Lots of aliases
+alias cal='cal -3'
+alias dmesg='dmesg -HL'
+alias df='df -h'
+alias du='du -ch'
+alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
+alias less='less -R'
+alias mkdir='mkdir -p -v'
+alias more='less'
+alias nano='nano -w'
 
-if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
-    if tmux has-session -t main 2>/dev/null; then
-        tmux attach -t main
-    else
-        tmux new -s main
-    fi
+# ls
+alias ls='ls -hF --color=auto'
+alias l.='ls -d .*'
+alias la='ls -A'
+alias ll='ls -l'
+alias lla='ls -lA'
+alias lld='ls -ld'
+
+# Safety features
+alias cp='cp -i'
+alias mv='mv -i'
+alias rm='rm -I' 
+alias ln='ln -i'
+alias chown='chown --preserve-root' # fail when attempting to change /
+alias chmod='chmod --preserve-root'
+alias chgrp='chgrp --preserve-root'
+
+# Id10t proofing
+alias :q=' exit'
+alias :Q=' exit'
+alias :x=' exit'
+alias cd..='cd ..'
+
+# Privileged access
+if [ $UID -ne 0 ]; then
+    alias scat='sudo cat'
+    alias svim='sudoedit'
+    alias root='sudo -i'
+    alias reboot='sudo systemctl reboot'
+    alias poweroff='sudo systemctl poweroff'
+    alias netctl='sudo netctl'
 fi
+
+# Optional aliases
+alias todo='todo.sh'
+alias diff='colordiff'
+alias top='htop'
+#alias yogurt='yaourt'
+
+# Pacman aliases
+#if necessary, replace 'pacman' with your favorite AUR helper and adapt the commands accordingly
+alias pac="sudo /usr/bin/pacman -S"     # default action    - install one or more packages
+alias pacu="/usr/bin/pacman -Syu"       # '[u]pdate'        - upgrade all packages to their newest version
+alias pacr="sudo /usr/bin/pacman -Rns"  # '[r]emove'        - uninstall one or more packages
+alias pacs="/usr/bin/pacman -Ss"        # '[s]earch'        - search for a package using one or more keywords
+alias paci="/usr/bin/pacman -Si"        # '[i]nfo'      - show information about a package
+alias paclo="/usr/bin/pacman -Qdt"      # '[l]ist [o]rphans'    - list all packages which are orphaned
+alias pacc="sudo /usr/bin/pacman -Scc"  # '[c]lean cache'   - delete all not currently installed package files
+alias paclf="/usr/bin/pacman -Ql"       # '[l]ist [f]iles'  - list all files installed by a given package
+alias pacexpl="/usr/bin/pacman -D --asexp"  # 'mark as [expl]icit'  - mark one or more packages as explicitly installed 
+alias pacimpl="/usr/bin/pacman -D --asdep"  # 'mark as [impl]icit'  - mark one or more packages as non explicitly installed
+
+# '[r]emove [o]rphans' - recursively remove ALL orphaned packages
+alias pacro="/usr/bin/pacman -Qtdq > /dev/null && sudo /usr/bin/pacman -Rns \$(/usr/bin/pacman -Qtdq | sed -e ':a;N;$!ba;s/\n/ /g')"
 
 # Display 256 colors
 alias colortest256='(x=`tput op` y=`printf %76s`;for i in {0..256};do o=00$i;echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x;done)'
@@ -162,3 +185,15 @@ GIT_PS1_SHOWDIRTYSTATE=yes
 GIT_PS1_SHOWSTASHSTATE=yes
 GIT_PS1_SHOWUNTRACKEDFILES=yes
 GIT_PS1_SHOWCOLORHINTS=yes
+
+# Local change support
+[[ -r $HOME/.bashrc_local ]] && source $HOME/.bashrc_local
+
+# launch tmux if not already in a session
+if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
+    if tmux has-session -t main 2>/dev/null; then
+        tmux attach -t main
+    else
+        tmux new -s main
+    fi
+fi
